### ISSUE TITLE
Compatibility with scalar type hints

### ISSUE THREAD

**Issue by Trainmaster** [php-fig/container#12]
It should be possible to support PSR-11 using:
```php
<?php
class Container extends \Psr\Container\ContainerInterface {
    public function get(string $id)
    {
        // ...
    }

    public function has(string $id)
    {
        // ...
    }
}
```
Any ideas?

**Comment by weierophinney** [comment]
The spec was written targeting all currently supported versions of PHP, which at this time also includes 5.6. As such, the interfaces do not use scalar type hints.

**Comment by lisachenko** [comment]
Related to #19

**Comment by BenMorel** [comment]
Note that all versions *not* supporting scalar type hints [are now EOL](https://www.php.net/supported-versions.php). Even PHP 7.0 is.

Isn't it time for a v2?

**Comment by Jean85** [comment]
PSRs are standards, hence immutable. Creating BC means breaking the PSR itself, it's not the same as updating a normal OSS project. We started a discussion around this issue: https://groups.google.com/d/topic/php-fig/OyC3plRYhqg/discussion
