### ISSUE TITLE
'-Interface' suffix on exceptions is inconsistent with other PSRs.

### ISSUE THREAD

**Issue by webdevxp** [php-fig/container#13]
There's no '-Interface' suffix in other PSRs with exception interfaces.
Should PSR-11 follow those PSRs?

**Comment by mnapoli** [comment]
The other PSRs were not consistent with the PSR rules, which this PSR is following. So it rather should be the other way around :)

**Comment by webdevxp** [comment]
I'm so sad :(.
Thank you for clarification.

**Comment by webdevxp** [comment]
Another question.
Is PSR-11 accepted?
I'm not sure because in php-fig website said it is in review phase.

**Comment by mnapoli** [comment]
@webdevxp yes it is accepted, the website is not up to date because of some build issue IIRC.

Closing :)
