### ISSUE TITLE
What is the purpose of `has`?

### ISSUE THREAD

**Issue by deleugpn** [php-fig/container#22]
I've read through a bunch of topics on container-interop and here that you guys talked A LOT about auto-wiring. Unfortunately the issue keeps popping up on Laravel because we decided that the container only returns `true` on `has` if objects are explicitly bound. One of the editors himself pointed it out here https://github.com/laravel/ideas/issues/803.

One thing I did not find in the discussions was `usage` instead of `implementations` and it's likely that you guys can point me to the right direction. 

Suppose the following usage: 

```
if ($container->has($identity)) {
    try {
        $concrete = $container->get($identity);

        //
    } catch (Psr\Container\ContainerExceptionInterface $e) {
        // This will never be a NotFoundExceptionInterface
    }
} else {
    // Not Found
}
```

Although a NotFoundException will never be thrown, a ContainerExceptionInterface can still be thrown. How much value did `has` added here versus the following: 

```
try {
    $concrete = $container->get($identity);

    //
} catch (Psr\Container\ContainerExceptionInterface $e) {
    if ($e instanceof NotFoundExceptionInterface) {
        // Not Found
    }
}
```

My point being: When using `$container->get($identity);`, a try-catch is basically a must-have and the value of `has` can still be achieved, if desired. What am I missing that makes me think `has` do more harm than good?

**Comment by weierophinney** [comment]
`has` exists for containers where you are _not_ doing autowiring, and for auto-wiring containers that "compile" to factories.

As an example, consider a container that uses factories to create instances. In those factories, developers can test for the existence of a service, and use defaults if the service is unavailable:

```php
function (ContainerInterface $container) use ($defaultOptions) {
    $db = $container->has(\Some\Db\Abstraction::class)
        ? $container->get(\Some\Db\Abstraction::class)
        : new \Some\Db\Abstraction($defaultOptions);
    return new \Some\Service\Using\A\DB($db);
}
```

Pimple, Aura.Di, zend-servicemanager, and several others use factory-based approaches, and the above is relatively common. It provides a way to have sane fallbacks when definitions are not found and/or cannot be auto-detected.

**Comment by deleugpn** [comment]
Thank you so much for your reply and insight on the matter, just a last followup before closing this. Would you agree that, according to the PSR-11 definition, `$container->get()` can still throw exception? And therefore the snippet would be safer as

```
function (ContainerInterface $container) use ($defaultOptions) {
    if ($container->has(\Some\Db\Abstraction::class)) {
        try {
            $db = $container->get(\Some\Db\Abstraction::class)
        
            return new \Some\Service\Using\A\DB($db);
        } catch (\Psr\Container\ContainerExceptionInterface $e) {

        }
    }

    return new \Some\Db\Abstraction($defaultOptions);
}
```

And this is exactly the moment where `has` loses it's meaning. `has` does not coexist nicely with `try/catch`. If you tell me that these containers never need a try/catch because of their implementation detail, then I can totally understand the snippet you presented. Otherwise, if an exception is to be expected, we can simply ignore the existence of `has`. We can even: 

```
function (ContainerInterface $container) use ($defaultOptions) {
    try {
        $db = $container->get(\Some\Db\Abstraction::class)
        
        return new \Some\Service\Using\A\DB($db);
    } catch (\Psr\Container\NotFoundExceptionInterface $e) {
        return new \Some\Db\Abstraction($defaultOptions);
    }
}
```

By doing this, we let any exception that is not related to NotFound bubble up while still providing a default. Or we could also catch all container exceptions and have an `instanceof` check for different default values, for whatever reason. My point being that there seems to be no scenario that `has` brings value when using try/catch and the PSR-11 description makes me feel like a try/catch is almost mandatory from a package developer perspective.

**Comment by mnapoli** [comment]
For reference https://github.com/container-interop/container-interop/issues/37 may help.

In PHP-DI I return true for autowired entries (see https://github.com/laravel/ideas/issues/803#issuecomment-331107805).

Basically `has()` means "I can provide this service". It is useful when combining several containers together: that helps the meta (aka parent) container to know which container to fetch the entry from.

> Would you agree that, according to the PSR-11 definition, $container->get() can still throw exception?

Yes, see https://github.com/php-fig/container/blob/master/src/ContainerInterface.php#L29-L30

But in your snippet why would you catch `ContainerExceptionInterface `? This is an exception that means something is very wrong, it should not be caught or silenced (that's the difference with NotFound). I even argued to remove that custom exception and throw a `\Exception`, see https://github.com/php-fig/container/pull/2

So your second snippet is wrong because some exceptions don't mean the entry doesn't exist, it means there is a configuration error and you should not fallback to something else.

**Comment by deleugpn** [comment]
Thanks for the attention and feedback.
