### ISSUE TITLE
Exception interfaces should extend Throwable

### ISSUE THREAD

**Issue by tux-rampage** [php-fig/container#40]
When running Static-Analysis like Psalm, they will report an invalid catch statement:

> InvalidCatch: Class/interface Psr\Container\NotFoundExceptionInterface cannot be caught

This happens because the Interfaces do not extend `Throwable`. This is correct since classes that do not implement `Throwable` cannot be used with `throw`: https://3v4l.org/NNDeW

**Comment by ChristophWurst** [comment]
See https://github.com/php-fig/container/issues/33 for some context. This was fixed, then reverted again.

**Comment by Jean85** [comment]
Fixed again in 1.1.2 and 2.0.2
