### ISSUE TITLE
Why are you bumping minimum php in patch releases?!

### ISSUE THREAD

**Issue by opengeek** [php-fig/container#42]
This is literally a backward compatibility break and should never happen in a patch release.

**Comment by drealecs** [comment]
How about minor? Can it happen in minor release? 😜

**Comment by Jean85** [comment]
> This is literally a backward compatibility break and should never happen in a patch release.

No, it's not. You'll find a lengthy explanation in #41, and more concisely in https://github.com/php-fig/container/issues/41#issuecomment-972768920

TL;DR: if you run `composer update` in an environment that doesn't match your prod, you're on your own.

Closing as duplicate of #41.
