### ISSUE TITLE
Why dependency on PHP 7.4.0

### ISSUE THREAD

**Issue by faisalrehmanlums** [php-fig/container#43]
Hi,

I'm unable to understand why this package **psr/container** require PHP 7.4.0 as its just collection on some interfaces. I think it should require not more than php: >=5.4.0 

Thanks!

**Comment by roxblnfk** [comment]
Don't worry the version 1.0.0 requires php >=5.3 https://github.com/php-fig/container/blob/b7ce3b176482dbbc1245ebf52b181af44c2cf55f/composer.json#L15

**Comment by Jean85** [comment]
Exactly. The bump on the PHP requirement was done in #20; you can read on the PSR process evolution here: https://www.php-fig.org/bylaws/psr-evolution/

**Comment by faisalrehmanlums** [comment]
Thanks for your reply :)
