### ISSUE TITLE
Error composer version

### ISSUE THREAD

**Issue by FuriosoJack** [php-fig/container#47]
I started getting the following error because now this parquet in its last tag added that it needs php>=7.4
![image](https://user-images.githubusercontent.com/26976637/206244635-38c2e9ec-aa1e-4df6-8071-c8157bbc2734.png)

The php version change should be in a version 3.0 and not in 2.0.2

**Comment by Jean85** [comment]
As already said in #42:

> You'll find a lengthy explanation in https://github.com/php-fig/container/issues/41, and more concisely in https://github.com/php-fig/container/issues/41#issuecomment-972768920
>
> TL;DR: if you run composer update in an environment that doesn't match your prod, you're on your own.

Closing as duplicate of #41.
