### ISSUE TITLE
Can't pull the package in via composer/packagist

### ISSUE THREAD

**Issue by stephan-v** [php-fig/container#7]
I am currently trying to pull this package in via composer like so:

```composer require psr/container```

from:

```https://packagist.org/packages/psr/container#dev-master```

But I am gettingt the following error:

> Problem 1
>                                                                                                           │    - The requested package psr/container could not be found in any version, there may be a typo in the pa
>                                                                                                           │ckage name.
>                                                                                                           │
>                                                                                                           │Potential causes:
>                                                                                                           │ - A typo in the package name
>                                                                                                           │ - The package is not available in a stable-enough version according to your minimum-stability setting
>                                                                                                           │   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
> 

Is there something wrong here? I can pull in other packages fine.

**Comment by KorvinSzanto** [comment]
Make sure your minimum stability is dev if you plan to pull in dev
libraries.

**Comment by stephan-v** [comment]
Thanks sorry for reading over the message. Have never seen this error before, got it working now. :+1:

**Comment by KorvinSzanto** [comment]
:+1:
