### ISSUE TITLE
Interface suffix?

### ISSUE THREAD

**Issue by greg0ire** [php-fig/container#8]
[The spec](https://github.com/php-fig/fig-standards/blob/master/proposed/container.md) uses it, the code does not. Is this being debated or has a decision already been taken about whether to add this suffix or not?

**Comment by mnapoli** [comment]
The spec is what is voted on so this package should mirror the spec. You are welcome to send a pull request to fix this code, or I'll find time this week-end to do it.

**Comment by greg0ire** [comment]
See #9 :)
